### PR TITLE
[WIP] Updated 0.6.1

### PR DESCRIPTION
**Pull request by fernandojsg**
I've been trying to update this to latest aframe but I've found one issue:

If we start the demo without webvr support and click start, the following line will throw an error: https://github.com/aframevr/a-saturday-night/blob/master/src/components/states/replay.js#L74
```
el.sceneEl.setAttribute('game-state', 'dancingTime', document.querySelector(soundSrc).getAttribute('duration'));
```

image

Because it tries to clone the selector resulting in a circular json error when trying to stringify it:

image

https://github.com/aframevr/aframe/blob/master/src/core/component.js#L366

Not sure if it's a bug on aframe or something we're doing wrong here that is not compatible with the latest version of aframe anymore. Any ideas @dmarcos @ngokevin

### CODE REVIEW

**Comment by caseyyee** [comment]
@fernandojsg I had prepared the update to 6.1 here:
https://github.com/aframevr/a-saturday-night/compare/master...caseyyee:aframe-update?expand=1

I didn't make a PR, because i was debating this issue:
https://github.com/aframevr/aframe/issues/2928

Having to deal with the async behavior is troublesome.  I feel this is really a bug since it worked prior to 6.1 update.

**Comment by fernandojsg** [comment]
@caseyyee cool, do you mind opening a PR with your code so we could review it too? Did you find the same issue I've described here?

**Comment by caseyyee** [comment]
@fernandojsg it's a different issue than your seeing.   I get a error on setAttribute.  This is definetly caused because of the element not being returned properly on the entity in issue https://github.com/aframevr/aframe/issues/2928.   

I will create the PR so that you can check it out and see if it works for you and we can compare notes.

**Comment by caseyyee** [comment]
@fernandojsg try/see https://github.com/aframevr/a-saturday-night/pull/118

**Comment by fernandojsg** [comment]
@caseyyee I will take a look. I've just noticed that with this https://github.com/aframevr/aframe/pull/2939 from @dmarcos it's fixed that first issue

**Comment by fernandojsg** [comment]
Closing this in favor to https://github.com/aframevr/a-saturday-night/pull/118

**Pull request closed without merging**
